services:
  server:
    container_name: server
    image: gradle:jdk19
    restart: always
    ports:
      - 8080:8080
      - 8761:8761
    volumes:
      - ./server:/workspace
    environment:
      - TZ=Asia/Seoul
      - LC_ALL:en_US.UTF-8
    command: sleep infinity
