spring:
  application:
    name: folder-gateway
  cloud:
    gateway:
      routes:
        - id: folder-api1
          uri: http://localhost:8081
          predicates:
            - Path=/api/**
          filters:
            - ApiFilter

        - id: folder-api2
          uri: http://localhost:8082
          predicates:
            - Path=/api/**


server:
  port: 8080
